
name: deploy_docker_ec2

on:
   push:
    branches: [ "master" ]
   pull_request:
    branches: [ "master" ]

   workflow_dispatch:
   
env: 
   docker_user: ${{ secrets.DOCKERHUB_USERNAME}}
   docker_password: ${{ secrets.DOCKERHUB_PASSWORD}}
   
jobs:
   
   pull_image:
     runs-on: ubuntu-latest
     #runs-on: [self-hosted, linux, x64 ]

     steps:
       - uses: actions/checkout@v3

       - name: docker login
         run: |
            sudo docker login -u $docker_user -p $docker_password

#       - name: pull MLflow server image
#         run: |
#          sudo docker pull scbnf99/mlflow:latest
#          sudo docker images
       - name: pull MLflow server image
         run: |
          sudo docker pull hello-world#nginx
          sudo docker images

       - name: run docker image
         run: |
          #sudo docker run -di --name nginx_server -p 8080:80 nginx  
          sudo docker run -di --name hello  hello-world
          curl http://127.0.0.1:8080/

         
